---
title: "L-Lysine_2uM_miRNA"
author: "Jessica A. Dozois"
date: '2023-05-02'
output: html_document
---
---
title: "L-Lysine 2uM_L-Lysine 2uM_miRNA"
author: "Jessica A. Dozois"
date: '2023-04-28'
output: html_document
---
#Loading librairies
```{r Librairies}
install.packages("pacman")
pacman::p_load(data.table,ggplot2,dplyr,forcats,here,ggpubr,car,rstatix)
```

#Creating folders
```{r}
dir.create(file.path("L-AA_screen2uM","Output", "Figures"), recursive=TRUE)
dir.create(file.path("L-AA_screen2uM","Output", "t.test_results", "L-Lysine"), recursive=TRUE)
```
#Importing data
```{r Importation}
Dosedf<-read.table(file.path("L-AA_screen2uM","Raw_Data", "L-Lysine.tsv"), header=T, sep="\t", comment.char = "") # 2460 obs 8 variables
Dosedf$Time<-as.factor(Dosedf$Time)
Dosedf$Pair<-as.factor(Dosedf$Pair)
Dosedf$Dose.uM.<-as.factor(Dosedf$Dose.uM.)
```
#Renaming variables
```{r}
Dosedf$Treatment<-recode_factor(Dosedf$Treatment, scrambled_miRNA= "Scramble miRNAs",plant_miRNA="Plant miRNAs" )
```

#Subsetting by mirna
```{r}
ath158a3p<-Dosedf[Dosedf$miRNA=="ath158a3p",]
ath158b<-Dosedf[Dosedf$miRNA=="ath158b",]
aof159<-Dosedf[Dosedf$miRNA=="aof159",]
ath827<-Dosedf[Dosedf$miRNA=="ath827",]
ath5642b<-Dosedf[Dosedf$miRNA=="ath5642b",]

```

```{r}
loop<-levels(Dosedf$Time)
#ath-miR158a-3p
i=0 
for(i in 1:41) 
{
Timepoint<-ath158a3p[ath158a3p$Time==loop[i],]
plant<- Timepoint[Timepoint$Treatment=="Plant miRNAs",]
planto<-plant[order(plant$Pair),]
mirplant<-planto$OD_600
scram<- Timepoint[Timepoint$Treatment=="Scramble miRNAs",]
scramo<-scram[order(scram$Pair),]
mirscram<-scramo$OD_600
differences<- as.data.frame(mirscram - mirplant)
outliers<-identify_outliers(differences) 
test<-shapiro_test(differences$`mirscram - mirplant`)
{
  if(nrow(outliers)>=1|test$p.value < 0.05)
    cat("Time:",loop[i]," ","p.value :", test$p.value, " ","Statistic:", test$statistic,"Outliers:",outliers$is.outlier,"\n", file=here("L-AA_screen2uM","Output","t.test_results", "L-Lysine","Assump_ath158a3p.txt"), append=T) 
  } 
 i=i+1}

i=0 
for(i in 1:41) 
{
Timepoint<-ath158a3p[ath158a3p$Time==loop[i],]
plant<- Timepoint[Timepoint$Treatment=="Plant miRNAs",]
planto<-plant[order(plant$Pair),]
mirplant<-planto$OD_600
scram<- Timepoint[Timepoint$Treatment=="Scramble miRNAs",]
scramo<-scram[order(scram$Pair),]
mirscram<-scramo$OD_600
test<-t.test(mirplant, mirscram, paired = TRUE, alternative = "greater")
{
  if(test$p.value < 0.05)
    cat("Time:",loop[i]," ","p.value :", test$p.value, " ","statistic:", test$statistic, "\n", file=here("L-AA_screen2uM","Output","t.test_results", "L-Lysine","ath158a3p_t.test.txt"), append=T) 
  } 
 i=i+1} #
i=0 
for(i in 1:41) 
{
Timepoint<-ath158a3p[ath158a3p$Time==loop[i],]
plant<- Timepoint[Timepoint$Treatment=="Plant miRNAs",]
planto<-plant[order(plant$Pair),]
mirplant<-planto$OD_600
scram<- Timepoint[Timepoint$Treatment=="Scramble miRNAs",]
scramo<-scram[order(scram$Pair),]
mirscram<-scramo$OD_600
test<-wilcox.test(mirplant, mirscram, paired = TRUE, alternative = "greater")
{
  if(test$p.value < 0.05)
    cat("Time:",loop[i]," ","p.value :", test$p.value, " ","statistic:", test$statistic, "\n", file=here("L-AA_screen2uM","Output","t.test_results", "L-Lysine","ath158a3p_wilcox.test.txt"), append=T) 
  } 
 i=i+1}


#ath-miR158b
i=0 
for(i in 1:41) 
{
Timepoint<-ath158b[ath158b$Time==loop[i],]
plant<- Timepoint[Timepoint$Treatment=="Plant miRNAs",]
planto<-plant[order(plant$Pair),]
mirplant<-planto$OD_600
scram<- Timepoint[Timepoint$Treatment=="Scramble miRNAs",]
scramo<-scram[order(scram$Pair),]
mirscram<-scramo$OD_600
differences<- as.data.frame(mirscram - mirplant)
outliers<-identify_outliers(differences) 
test<-shapiro_test(differences$`mirscram - mirplant`)
{
  if(nrow(outliers)>=1|test$p.value < 0.05)
    cat("Time:",loop[i]," ","p.value :", test$p.value, " ","Statistic:", test$statistic,"Outliers:",outliers$is.outlier,"\n", file=here("L-AA_screen2uM","Output","t.test_results", "L-Lysine","Assump_ath158b.txt"), append=T) 
  } 
 i=i+1}

i=0 
for(i in 1:41) 
{
Timepoint<-ath158b[ath158b$Time==loop[i],]
plant<- Timepoint[Timepoint$Treatment=="Plant miRNAs",]
planto<-plant[order(plant$Pair),]
mirplant<-planto$OD_600
scram<- Timepoint[Timepoint$Treatment=="Scramble miRNAs",]
scramo<-scram[order(scram$Pair),]
mirscram<-scramo$OD_600
test<-t.test(mirplant, mirscram, paired = TRUE, alternative = "greater")
{
  if(test$p.value < 0.05)
    cat("Time:",loop[i]," ","p.value :", test$p.value, " ","statistic:", test$statistic, "\n", file=here("L-AA_screen2uM","Output","t.test_results", "L-Lysine","ath158b_t.test.txt"), append=T) 
  } 
 i=i+1} #
i=0 
for(i in 1:41) 
{
Timepoint<-ath158b[ath158b$Time==loop[i],]
plant<- Timepoint[Timepoint$Treatment=="Plant miRNAs",]
planto<-plant[order(plant$Pair),]
mirplant<-planto$OD_600
scram<- Timepoint[Timepoint$Treatment=="Scramble miRNAs",]
scramo<-scram[order(scram$Pair),]
mirscram<-scramo$OD_600
test<-wilcox.test(mirplant, mirscram, paired = TRUE, alternative = "greater")
{
  if(test$p.value < 0.05)
    cat("Time:",loop[i]," ","p.value :", test$p.value, " ","statistic:", test$statistic, "\n", file=here("L-AA_screen2uM","Output","t.test_results", "L-Lysine","ath158b_wilcox.test.txt"), append=T) 
  } 
 i=i+1}

#aof-miR159
i=0 
for(i in 1:41) 
{
Timepoint<-aof159[aof159$Time==loop[i],]
plant<- Timepoint[Timepoint$Treatment=="Plant miRNAs",]
planto<-plant[order(plant$Pair),]
mirplant<-planto$OD_600
scram<- Timepoint[Timepoint$Treatment=="Scramble miRNAs",]
scramo<-scram[order(scram$Pair),]
mirscram<-scramo$OD_600
differences<- as.data.frame(mirscram - mirplant)
outliers<-identify_outliers(differences) 
test<-shapiro_test(differences$`mirscram - mirplant`)
{
  if(nrow(outliers)>=1|test$p.value < 0.05)
    cat("Time:",loop[i]," ","p.value :", test$p.value, " ","Statistic:", test$statistic,"Outliers:",outliers$is.outlier,"\n", file=here("L-AA_screen2uM","Output","t.test_results", "L-Lysine","Assump_aof159.txt"), append=T) 
  } 
 i=i+1}

i=0 
for(i in 1:41) 
{
Timepoint<-aof159[aof159$Time==loop[i],]
plant<- Timepoint[Timepoint$Treatment=="Plant miRNAs",]
planto<-plant[order(plant$Pair),]
mirplant<-planto$OD_600
scram<- Timepoint[Timepoint$Treatment=="Scramble miRNAs",]
scramo<-scram[order(scram$Pair),]
mirscram<-scramo$OD_600
test<-t.test(mirplant, mirscram, paired = TRUE, alternative = "greater")
{
  if(test$p.value < 0.05)
    cat("Time:",loop[i]," ","p.value :", test$p.value, " ","statistic:", test$statistic, "\n", file=here("L-AA_screen2uM","Output","t.test_results", "L-Lysine","aof159_t.test.txt"), append=T) 
  } 
 i=i+1} #
i=0 
for(i in 1:41) 
{
Timepoint<-aof159[aof159$Time==loop[i],]
plant<- Timepoint[Timepoint$Treatment=="Plant miRNAs",]
planto<-plant[order(plant$Pair),]
mirplant<-planto$OD_600
scram<- Timepoint[Timepoint$Treatment=="Scramble miRNAs",]
scramo<-scram[order(scram$Pair),]
mirscram<-scramo$OD_600
test<-wilcox.test(mirplant, mirscram, paired = TRUE, alternative = "greater")
{
  if(test$p.value < 0.05)
    cat("Time:",loop[i]," ","p.value :", test$p.value, " ","statistic:", test$statistic, "\n", file=here("L-AA_screen2uM","Output","t.test_results", "L-Lysine","aof159_wilcox.test.txt"), append=T) 
  } 
 i=i+1}

#ath-miR827
i=0 
for(i in 1:41) 
{
Timepoint<-ath827[ath827$Time==loop[i],]
plant<- Timepoint[Timepoint$Treatment=="Plant miRNAs",]
planto<-plant[order(plant$Pair),]
mirplant<-planto$OD_600
scram<- Timepoint[Timepoint$Treatment=="Scramble miRNAs",]
scramo<-scram[order(scram$Pair),]
mirscram<-scramo$OD_600
differences<- as.data.frame(mirscram - mirplant)
outliers<-identify_outliers(differences) 
test<-shapiro_test(differences$`mirscram - mirplant`)
{
  if(nrow(outliers)>=1|test$p.value < 0.05)
    cat("Time:",loop[i]," ","p.value :", test$p.value, " ","Statistic:", test$statistic,"Outliers:",outliers$is.outlier,"\n", file=here("L-AA_screen2uM","Output","t.test_results", "L-Lysine","Assump_ath827.txt"), append=T) 
  } 
 i=i+1}

i=0 
for(i in 1:41) 
{
Timepoint<-ath827[ath827$Time==loop[i],]
plant<- Timepoint[Timepoint$Treatment=="Plant miRNAs",]
planto<-plant[order(plant$Pair),]
mirplant<-planto$OD_600
scram<- Timepoint[Timepoint$Treatment=="Scramble miRNAs",]
scramo<-scram[order(scram$Pair),]
mirscram<-scramo$OD_600
test<-t.test(mirplant, mirscram, paired = TRUE, alternative = "greater")
{
  if(test$p.value < 0.05)
    cat("Time:",loop[i]," ","p.value :", test$p.value, " ","statistic:", test$statistic, "\n", file=here("L-AA_screen2uM","Output","t.test_results", "L-Lysine","ath827_t.test.txt"), append=T) 
  } 
 i=i+1} #
i=0 
for(i in 1:41) 
{
Timepoint<-ath827[ath827$Time==loop[i],]
plant<- Timepoint[Timepoint$Treatment=="Plant miRNAs",]
planto<-plant[order(plant$Pair),]
mirplant<-planto$OD_600
scram<- Timepoint[Timepoint$Treatment=="Scramble miRNAs",]
scramo<-scram[order(scram$Pair),]
mirscram<-scramo$OD_600
test<-wilcox.test(mirplant, mirscram, paired = TRUE, alternative = "greater")
{
  if(test$p.value < 0.05)
    cat("Time:",loop[i]," ","p.value :", test$p.value, " ","statistic:", test$statistic, "\n", file=here("L-AA_screen2uM","Output","t.test_results", "L-Lysine","ath827_wilcox.test.txt"), append=T) 
  } 
 i=i+1}

#ath-miR5642b
i=0 
for(i in 1:41) 
{
Timepoint<-ath5642b[ath5642b$Time==loop[i],]
plant<- Timepoint[Timepoint$Treatment=="Plant miRNAs",]
planto<-plant[order(plant$Pair),]
mirplant<-planto$OD_600
scram<- Timepoint[Timepoint$Treatment=="Scramble miRNAs",]
scramo<-scram[order(scram$Pair),]
mirscram<-scramo$OD_600
differences<- as.data.frame(mirscram - mirplant)
outliers<-identify_outliers(differences) 
test<-shapiro_test(differences$`mirscram - mirplant`)
{
  if(nrow(outliers)>=1|test$p.value < 0.05)
    cat("Time:",loop[i]," ","p.value :", test$p.value, " ","Statistic:", test$statistic,"Outliers:",outliers$is.outlier,"\n", file=here("L-AA_screen2uM","Output","t.test_results", "L-Lysine","Assump_ath5642b.txt"), append=T) 
  } 
 i=i+1}

i=0 
for(i in 1:41) 
{
Timepoint<-ath5642b[ath5642b$Time==loop[i],]
plant<- Timepoint[Timepoint$Treatment=="Plant miRNAs",]
planto<-plant[order(plant$Pair),]
mirplant<-planto$OD_600
scram<- Timepoint[Timepoint$Treatment=="Scramble miRNAs",]
scramo<-scram[order(scram$Pair),]
mirscram<-scramo$OD_600
test<-t.test(mirplant, mirscram, paired = TRUE, alternative = "greater")
{
  if(test$p.value < 0.05)
    cat("Time:",loop[i]," ","p.value :", test$p.value, " ","statistic:", test$statistic, "\n", file=here("L-AA_screen2uM","Output","t.test_results", "L-Lysine","ath5642b_t.test.txt"), append=T) 
  } 
 i=i+1} #
i=0 
for(i in 1:41) 
{
Timepoint<-ath5642b[ath5642b$Time==loop[i],]
plant<- Timepoint[Timepoint$Treatment=="Plant miRNAs",]
planto<-plant[order(plant$Pair),]
mirplant<-planto$OD_600
scram<- Timepoint[Timepoint$Treatment=="Scramble miRNAs",]
scramo<-scram[order(scram$Pair),]
mirscram<-scramo$OD_600
test<-wilcox.test(mirplant, mirscram, paired = TRUE, alternative = "greater")
{
  if(test$p.value < 0.05)
    cat("Time:",loop[i]," ","p.value :", test$p.value, " ","statistic:", test$statistic, "\n", file=here("L-AA_screen2uM","Output","t.test_results", "L-Lysine","ath5642b_wilcox.test.txt"), append=T) 
  } 
 i=i+1}

```


#boxplots for every miRNA
```{r}
box158a3p<- ggplot( ath158a3p, aes(x=Time, y=OD_600 ,fill=Treatment, colour=Treatment)) +
    geom_boxplot(outlier.shape = NA, alpha=0.4) +
  geom_point(pch = 21, position = position_jitterdodge())+
 theme_classic() + 
  scale_fill_manual(values = c("#457b9d","grey"))+
scale_colour_manual(values = c("#457b9d","grey"))
a<-box158a3p  +labs(x="Time (hours)", y="Optical Density (600nm)")+ ylim(0,2.5)+ theme(legend.title = element_text(size = 14) ,legend.text = element_text(size=12))+ ggtitle("L-Lysine 2uM ath-miR158a-3p")+ theme(plot.title = element_text(size = 14))
a<-a+annotate("rect",xmin = 27.5, xmax=30.5, ymin = 0, ymax=2.5,alpha=.2, fill="#457b9d")+annotate("rect",xmin = 36.5, xmax=37.5, ymin = 0, ymax=1.8,alpha=.2, fill="#457b9d")

boxath158b<- ggplot( ath158b, aes(x=Time, y=OD_600 ,fill=Treatment, colour=Treatment)) +
    geom_boxplot(outlier.shape = NA, alpha=0.4) +
  geom_point(pch = 21, position = position_jitterdodge())+
 theme_classic() + 
  scale_fill_manual(values = c("#457b9d","grey"))+
scale_colour_manual(values = c("#457b9d","grey"))
b<-boxath158b  +labs(x="Time (hours)", y="Optical Density (600nm)")+ ylim(0,1.8)+ theme(legend.title = element_text(size = 14) ,legend.text = element_text(size=12))+ ggtitle("L-Lysine 2uM ath-miR158b")+ theme(plot.title = element_text(size = 14))



boxaof159<- ggplot( aof159, aes(x=Time, y=OD_600 ,fill=Treatment, colour=Treatment)) +
    geom_boxplot(outlier.shape = NA, alpha=0.4) +
  geom_point(pch = 21, position = position_jitterdodge())+
 theme_classic() + 
  scale_fill_manual(values = c("#457b9d","grey"))+
scale_colour_manual(values = c("#457b9d","grey"))
c<-boxaof159  +labs(x="Time (hours)", y="Optical Density (600nm)")+ ylim(0,2)+ theme(legend.title = element_text(size = 14) ,legend.text = element_text(size=12))+ ggtitle("L-Lysine 2uM aof-miR159")+ theme(plot.title = element_text(size = 14))
c<-c+annotate("rect",xmin = 26.5, xmax=29.5, ymin = 0, ymax=2,alpha=.2, fill="#457b9d")+annotate("rect",xmin = 31.5, xmax=33.5, ymin = 0, ymax=1.8,alpha=.2, fill="#457b9d")+annotate("rect",xmin = 35.5, xmax=36.5, ymin = 0, ymax=1.8,alpha=.2, fill="#457b9d")


boxath827<- ggplot( ath827, aes(x=Time, y=OD_600 ,fill=Treatment, colour=Treatment)) +
    geom_boxplot(outlier.shape = NA, alpha=0.4) +
  geom_point(pch = 21, position = position_jitterdodge())+
 theme_classic() + 
  scale_fill_manual(values = c("#457b9d","grey"))+
scale_colour_manual(values = c("#457b9d","grey"))
d<-boxath827  +labs(x="Time (hours)", y="Optical Density (600nm)")+ ylim(0,2)+ theme(legend.title = element_text(size = 14) ,legend.text = element_text(size=12))+ ggtitle("L-Lysine 2uM ath-miR827")+ theme(plot.title = element_text(size = 14))
d<-d+annotate("rect",xmin = 21.5, xmax=23.5, ymin = 0, ymax=2,alpha=.2, fill="#457b9d")+annotate("rect",xmin = 30.5, xmax=31.5, ymin = 0, ymax=1.8,alpha=.2, fill="#457b9d")+annotate("rect",xmin = 36.5, xmax=37.5, ymin = 0, ymax=1.8,alpha=.2, fill="#457b9d")


boxath5642b<- ggplot( ath5642b, aes(x=Time, y=OD_600 ,fill=Treatment, colour=Treatment)) +
    geom_boxplot(outlier.shape = NA, alpha=0.4) +
  geom_point(pch = 21, position = position_jitterdodge())+
 theme_classic() + 
  scale_fill_manual(values = c("#457b9d","grey"))+
scale_colour_manual(values = c("#457b9d","grey"))
e<-boxath5642b  +labs(x="Time (hours)", y="Optical Density (600nm)")+ ylim(0,1.8)+ theme(legend.title = element_text(size = 14) ,legend.text = element_text(size=12))+ ggtitle("L-Lysine 2uM ath-miR5642b")+ theme(plot.title = element_text(size = 14))
e<-e+annotate("rect",xmin = 39.5, xmax=40.5, ymin = 0, ymax=1.8,alpha=.2, fill="#457b9d")
  
figdoserep<- ggarrange(a,b,c,d,e,common.legend = T, ncol=2,nrow=3)
figdoserep
ggsave(figdoserep, file=here("L-AA_screen2uM","Output","Figures","L-Lysine_2uM.jpg"),width = 40, height = 40, units = "cm")

```

